// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consignment/consignment.proto

package consPKG

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Consignment struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32        `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Container            []*Container `protobuf:"bytes,4,rep,name=container,proto3" json:"container,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{0}
}

func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (m *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(m, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainer() []*Container {
	if m != nil {
		return m.Container
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Origin               string   `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	CustomerId           string   `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Response struct {
	Created              bool           `protobuf:"varint,1,opt,name=Created,proto3" json:"Created,omitempty"`
	Consignment          *Consignment   `protobuf:"bytes,2,opt,name=consignment,proto3" json:"consignment,omitempty"`
	Consignments         []*Consignment `protobuf:"bytes,3,rep,name=consignments,proto3" json:"consignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func (m *Response) GetConsignments() []*Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{3}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Consignment)(nil), "consPKG.Consignment")
	proto.RegisterType((*Container)(nil), "consPKG.Container")
	proto.RegisterType((*Response)(nil), "consPKG.Response")
	proto.RegisterType((*Request)(nil), "consPKG.Request")
}

func init() {
	proto.RegisterFile("proto/consignment/consignment.proto", fileDescriptor_e5e5ab05dfa973d5)
}

var fileDescriptor_e5e5ab05dfa973d5 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xcf, 0x4e, 0x32, 0x31,
	0x10, 0xff, 0x96, 0x05, 0x96, 0x9d, 0xfd, 0xa2, 0x32, 0x31, 0xd8, 0xe8, 0xc1, 0xcd, 0x7a, 0xe1,
	0x84, 0x06, 0x13, 0xc3, 0xc9, 0x0b, 0x07, 0x42, 0xbc, 0x98, 0xfa, 0x00, 0x06, 0xb7, 0x13, 0x6c,
	0x22, 0x2d, 0xb6, 0x05, 0xdf, 0xc2, 0xa3, 0x8f, 0xe0, 0x73, 0x1a, 0xba, 0x2c, 0xd4, 0xc8, 0x6d,
	0x7f, 0xff, 0xfa, 0x9b, 0xce, 0x16, 0xae, 0x96, 0x46, 0x3b, 0x7d, 0x5d, 0x6a, 0x65, 0xe5, 0x5c,
	0x2d, 0x48, 0xb9, 0xf0, 0x7b, 0xe0, 0x55, 0x4c, 0x36, 0xd4, 0xe3, 0xc3, 0xa4, 0xf8, 0x8e, 0x20,
	0x1b, 0xef, 0x65, 0x3c, 0x82, 0x86, 0x14, 0x2c, 0xca, 0xa3, 0x7e, 0xca, 0x1b, 0x52, 0x60, 0x0e,
	0x99, 0x20, 0x5b, 0x1a, 0xb9, 0x74, 0x52, 0x2b, 0xd6, 0xf0, 0x42, 0x48, 0x61, 0x0f, 0xda, 0x1f,
	0x24, 0xe7, 0xaf, 0x8e, 0xc5, 0x79, 0xd4, 0x6f, 0xf1, 0x2d, 0xc2, 0x1b, 0x48, 0x4b, 0xad, 0xdc,
	0x4c, 0x2a, 0x32, 0xac, 0x99, 0xc7, 0xfd, 0x6c, 0x88, 0x83, 0x6d, 0xed, 0x60, 0x5c, 0x2b, 0x7c,
	0x6f, 0xc2, 0x0b, 0x48, 0xd7, 0x64, 0x2d, 0xbd, 0x3d, 0x4b, 0xc1, 0x5a, 0xbe, 0xa9, 0x53, 0x11,
	0x53, 0x51, 0x2c, 0x20, 0xdd, 0x85, 0xfe, 0x4c, 0xd9, 0x83, 0xb6, 0x36, 0x72, 0x2e, 0xeb, 0x01,
	0xb7, 0x08, 0x2f, 0x21, 0x2b, 0x57, 0xd6, 0xe9, 0x05, 0x99, 0xcd, 0x99, 0xb1, 0x17, 0xa1, 0xa6,
	0xa6, 0x02, 0xcf, 0x20, 0x59, 0xd9, 0x4a, 0x6c, 0x56, 0xc9, 0x0d, 0x9c, 0x8a, 0xe2, 0x2b, 0x82,
	0x0e, 0x27, 0xbb, 0xd4, 0xca, 0x12, 0x32, 0x48, 0xc6, 0x86, 0x66, 0x8e, 0xaa, 0xce, 0x0e, 0xaf,
	0x21, 0xde, 0x41, 0x16, 0x2c, 0xd7, 0xb7, 0x67, 0xc3, 0xd3, 0xf0, 0x9a, 0xb5, 0xc6, 0x43, 0x23,
	0x8e, 0xe0, 0x7f, 0x00, 0x2d, 0x8b, 0xfd, 0x7e, 0x0e, 0x07, 0x7f, 0x39, 0x8b, 0x14, 0x12, 0x4e,
	0xef, 0x2b, 0xb2, 0x6e, 0xf8, 0x19, 0x01, 0x06, 0xc6, 0x27, 0x32, 0x6b, 0x59, 0x12, 0xde, 0x43,
	0xb7, 0x1a, 0x2f, 0xfc, 0xaf, 0x07, 0x8f, 0x3e, 0xef, 0xee, 0xd8, 0xfa, 0xae, 0xc5, 0x3f, 0x1c,
	0xc1, 0xf1, 0x84, 0x5c, 0x60, 0xb3, 0x78, 0x12, 0xf8, 0x7c, 0xf7, 0xc1, 0xe4, 0x4b, 0xdb, 0x3f,
	0xae, 0xdb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xb9, 0x20, 0x63, 0x83, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ConsignmentService service

type ConsignmentServiceClient interface {
	CreateConsignment(ctx context.Context, in *Consignment, opts ...client.CallOption) (*Response, error)
	GetConsignments(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type consignmentServiceClient struct {
	c           client.Client
	serviceName string
}

func NewConsignmentServiceClient(serviceName string, c client.Client) ConsignmentServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "consPKG"
	}
	return &consignmentServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *consignmentServiceClient) CreateConsignment(ctx context.Context, in *Consignment, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ConsignmentService.CreateConsignment", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consignmentServiceClient) GetConsignments(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ConsignmentService.GetConsignments", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ConsignmentService service

type ConsignmentServiceHandler interface {
	CreateConsignment(context.Context, *Consignment, *Response) error
	GetConsignments(context.Context, *Request, *Response) error
}

func RegisterConsignmentServiceHandler(s server.Server, hdlr ConsignmentServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&ConsignmentService{hdlr}, opts...))
}

type ConsignmentService struct {
	ConsignmentServiceHandler
}

func (h *ConsignmentService) CreateConsignment(ctx context.Context, in *Consignment, out *Response) error {
	return h.ConsignmentServiceHandler.CreateConsignment(ctx, in, out)
}

func (h *ConsignmentService) GetConsignments(ctx context.Context, in *Request, out *Response) error {
	return h.ConsignmentServiceHandler.GetConsignments(ctx, in, out)
}
