version: '3.1'

services:
  consignment-service:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      DB_HOST: "datastore:27017"
      MICRO_REGISTRY: "mdns"
      MICRO_SERVER_ADDRESS: ":50051"

  vessel-service:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      DB_HOST: "datastore:27017"
      MICRO_REGISTRY: "mdns"
      MICRO_SERVER_ADDRESS: "127.0.0.1:50052"

  user-service:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      DB_HOST: "database"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_PORT: "5432"
      MICRO_SERVER_ADDRESS: ":50053"
      MICRO_REGISTRY: "mdns"
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "natsbase:4222"

    depends_on:
      - database

  email-service:
    build: ./email-service
    ports:
      - 50054:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50053"
      MICRO_REGISTRY: "mdns"
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "natsbase:4222"

  consignment-client:
    build: ./consignment-client
    environment:
      MICRO_REGISTRY: "mdns"

  user-client:
    build: ./user-client
    environment:
      MICRO_REGISTRY: "mdns"

  datastore:
    image: mongo
    ports:
      - 27017:27017

  database:
    image: postgres
    ports:
      - 5432:5432

  natsbase:
    image: nats
    ports:
      - 4222:4222
